version: '3'

services:
    project-service_local:
        container_name: project-service_local
        build: .
        command: >
            sh -c "python src/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        env_file:
            - '.env'