version: '3'

services:
    project-service:
        container_name: project-service
        build: .
        command: "python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./src/:/code
        env_file:
            - '.env'
        ports:
            - 8000:8000
