version: '3'

services:
    project-service:
        container_name: project-service
        build: .
        command: >
            bash -c "python projectservice/manage.py loaddata projectservice/*/fixtures/*.yaml
            && python projectservice/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        env_file:
            - '.env'
        network_mode: host
