# Generated by Django 4.0 on 2022-01-04 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0004_rule_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='rule_category',
        ),
    ]
