# Generated by Django 4.0 on 2022-01-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0007_rule_transaciton_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='onboarding',
        ),
    ]
