# Generated by Django 4.0 on 2022-03-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0009_alter_rule_execution_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='transaciton_category',
            new_name='transaction_category',
        ),
    ]
