# Generated by Django 4.0 on 2021-12-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
