# Generated by Django 4.0 on 2021-12-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='from_account',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='to_account',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
