apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: default
  labels:
    app: project-service
spec:
  type: NodePort
  selector:
    app: project-service
  ports:
    - port: 8000
      targetPort: 8000
